// Generado por CMOF Admin — 18/6/2026, 6:28:00 p.m.
var proyectosData = [
  {
    "id": "p1780987587201",
    "codigo": "H-BÖDN",
    "nombre": "BÖDEN HOTEL & SPA",
    "tipologia": "Hospitality",
    "estado": "Proyecto",
    "anio_inicio": "2017",
    "anio_fin": "2021",
    "superficie": "5579",
    "ciudad": "Villa General Belgrano",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 57 32",
    "lat_hem": "S",
    "lon": "064 57 32",
    "lon_hem": "W",
    "altitud": "787",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "H-BÖDN-01.png",
      "H-BÖDN-02.png",
      "H-BÖDN-03.png",
      "H-BÖDN-04.png",
      "H-BÖDN-05.png",
      "H-BÖDN-06.png",
      "H-BÖDN-07.png",
      "H-BÖDN-08.png",
      "H-BÖDN-09.png",
      "H-BÖDN-10.png",
      "H-BÖDN-11.png",
      "H-BÖDN-12.png",
      "H-BÖDN-13.png"
    ]
  },
  {
    "id": "p1780987781964",
    "codigo": "K-EGSC",
    "nombre": "Casa ELENA & GUILLERMO",
    "tipologia": "Residential",
    "estado": "En obra",
    "anio_inicio": "2023",
    "anio_fin": "2026",
    "superficie": "430",
    "ciudad": "San Clemente",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 41 36",
    "lat_hem": "S",
    "lon": "064 38 21",
    "lon_hem": "W",
    "altitud": "996",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": []
  },
  {
    "id": "p1780988025043",
    "codigo": "K-GELC.307",
    "nombre": "Casa G&E 307",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2022",
    "anio_fin": "2023",
    "superficie": "363",
    "ciudad": "La Cuesta - La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 21 43",
    "lat_hem": "S",
    "lon": "064 19 34",
    "lon_hem": "W",
    "altitud": "610",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-GELC.307-01.png",
      "K-GELC.307-02.png"
    ]
  },
  {
    "id": "p1780988370950",
    "codigo": "K-PMIY",
    "nombre": "Casa PABLO & RENATA",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2017",
    "anio_fin": "2019",
    "superficie": "316",
    "ciudad": "Inti Yaco - Calamuchita",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 56 50",
    "lat_hem": "S",
    "lon": "064 41 57",
    "lon_hem": "W",
    "altitud": "1129",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-PMIY-01.png",
      "K-PMIY-02.png",
      "K-PMIY-03.png",
      "K-PMIY-04.png",
      "K-PMIY-05.png",
      "K-PMIY-06.png",
      "K-PMIY-07.png"
    ]
  },
  {
    "id": "p1781033858892",
    "codigo": "K-EGLR.302",
    "nombre": "Casa ELENA & GUILLERMO - LR",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2012",
    "anio_fin": "2013",
    "superficie": "513",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 43",
    "lat_hem": "S",
    "lon": "064 18 54",
    "lon_hem": "W",
    "altitud": "506",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-EGLR.202-01.png",
      "K-EGLR.202-02.png",
      "K-EGLR.202-03.png",
      "K-EGLR.202-04.png",
      "K-EGLR.202-05.png",
      "K-EGLR.202-06.png",
      "K-GELC.307-01.png"
    ]
  },
  {
    "id": "p1781037475837",
    "codigo": "K-GELC.307",
    "nombre": "Casa GLENDA & ELADIO",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2021",
    "anio_fin": "2022",
    "superficie": "392",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 21 40",
    "lat_hem": "S",
    "lon": "064 19 34",
    "lon_hem": "W",
    "altitud": "562",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-GELC.307-01.png",
      "K-GELC.307-02.png"
    ]
  },
  {
    "id": "p1781039870192",
    "codigo": "M-JQEP",
    "nombre": "JAQUE PRODUCTORA",
    "tipologia": "Otros",
    "estado": "Construido",
    "anio_inicio": "2008",
    "anio_fin": "2021",
    "superficie": "393",
    "ciudad": "Córdoba",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 59",
    "lat_hem": "S",
    "lon": "064 14 27",
    "lon_hem": "W",
    "altitud": "449",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "M-JQEP-01.png",
      "M-JQEP-02.png",
      "M-JQEP-03.png"
    ]
  }
];
