// Generado por CMOF Admin — 21/6/2026, 12:33:42 a.m.
var proyectosData = [
  {
    "id": "p1780987587201",
    "codigo": "H-BÖDN",
    "nombre": "BÖDEN HOTEL & SPA",
    "tipologia": "H",
    "estado": "Construido",
    "anio_inicio": "2017",
    "anio_fin": "2021",
    "superficie": "5579",
    "ciudad": "Villa General Belgrano",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 57 32",
    "lat_hem": "S",
    "lon": "064 33 12",
    "lon_hem": "W",
    "altitud": "787",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "P-01-01 - BODEN HOTEL Y SPA-01.jpg",
      "P-01-02 - BODEN HOTEL Y SPA-02.jpg",
      "P-01-03 - BODEN HOTEL Y SPA-02.jpg",
      "P-01-03 - BODEN HOTEL Y SPA-03.jpg",
      "P-01-04 - BODEN HOTEL Y SPA-06.jpg",
      "P-01-04 - BODEN HOTEL Y SPA-07.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-12.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-14.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-15.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-16.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-18.jpg",
      "P-01-06 - BODEN HOTEL Y SPA-11.jpg",
      "P-01-07 - BODEN HOTEL Y SPA-12.jpg"
    ],
    "web_es": "BÖDEN Hotel & Spa nace de la búsqueda de una hospitalidad contemporánea profundamente vinculada con el paisaje serrano y con una idea de bienestar asociada a la calma, la naturaleza y el tiempo desacelerado. Ubicado en Villa General Belgrano, el proyecto propone una arquitectura moderna de materialidad cálida, concebida para integrarse con el entorno y potenciar sus cualidades.\n\nLa experiencia se estructura a partir de tres elementos esenciales —Tierra, Agua y Cielo—, que dan sentido a los espacios y al modo en que el huésped recorre y habita el conjunto. La luz natural, las visuales abiertas y las áreas destinadas al descanso forman parte de una misma narrativa arquitectónica.\n\nMás que un edificio, BÖDEN busca construir una atmósfera. Una experiencia de lujo sereno, donde el diseño no persigue el exceso sino la autenticidad, y donde cada decisión espacial contribuye a generar bienestar, memoria y una conexión genuina con el lugar. La hospitalidad no se mide únicamente en metros cuadrados, sino en la capacidad de transformar una estadía en un recuerdo perdurable.\n\nEl programa contempla 72 habitaciones distribuidas en distintas categorías, diferenciadas por sus dimensiones, visuales y expansiones exteriores. Se complementa con espacios gastronómicos y áreas comunes concebidas para ofrecer una experiencia integral. El layout fue desarrollado a partir de un estudio minucioso de los aspectos funcionales y operativos, optimizando las relaciones entre áreas públicas, privadas y de servicio para lograr una operación eficiente y prácticamente invisible.\n\nEn el corazón del proyecto se encuentra el Spa & Wellness Center, uno de los principales protagonistas de la experiencia BÖDEN. Organizado alrededor de un completo circuito de aguas y bienestar, incorpora piscina cubierta climatizada, hidromasajes interiores y exteriores, saunas, duchas sensoriales, salas temáticas de masajes y espacios de relajación. La secuencia de los ambientes y su relación con la luz y el paisaje fueron concebidas para transformar el bienestar en una experiencia arquitectónica, integrando arquitectura, paisaje y hospitalidad en una única visión de diseño.",
    "web_en": ""
  },
  {
    "id": "p1780987781964",
    "codigo": "K-EGSC",
    "nombre": "Casa ELENA & GUILLERMO",
    "tipologia": "Residential",
    "estado": "En obra",
    "anio_inicio": "2023",
    "anio_fin": "2026",
    "superficie": "430",
    "ciudad": "San Clemente",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 41 36",
    "lat_hem": "S",
    "lon": "064 38 21",
    "lon_hem": "W",
    "altitud": "996",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": []
  },
  {
    "id": "p1780988025043",
    "codigo": "K-GELC.307",
    "nombre": "Casa G&E 307",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2022",
    "anio_fin": "2023",
    "superficie": "363",
    "ciudad": "La Cuesta - La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 21 43",
    "lat_hem": "S",
    "lon": "064 19 34",
    "lon_hem": "W",
    "altitud": "610",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-GELC.307-01.png",
      "K-GELC.307-02.png"
    ]
  },
  {
    "id": "p1780988370950",
    "codigo": "K-PMIY",
    "nombre": "Casa PABLO & RENATA",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2017",
    "anio_fin": "2019",
    "superficie": "316",
    "ciudad": "Inti Yaco - Calamuchita",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 56 50",
    "lat_hem": "S",
    "lon": "064 41 57",
    "lon_hem": "W",
    "altitud": "1129",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-PMIY-01.png",
      "K-PMIY-02.png",
      "K-PMIY-03.png",
      "K-PMIY-04.png",
      "K-PMIY-05.png",
      "K-PMIY-06.png",
      "K-PMIY-07.png"
    ]
  },
  {
    "id": "p1781033858892",
    "codigo": "K-EGLR.302",
    "nombre": "Casa ELENA & GUILLERMO - LR",
    "tipologia": "H",
    "estado": "Construido",
    "anio_inicio": "2012",
    "anio_fin": "2013",
    "superficie": "513",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 43",
    "lat_hem": "S",
    "lon": "064 18 54",
    "lon_hem": "W",
    "altitud": "506",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-EGLR.202-01.png",
      "K-EGLR.202-02.png",
      "K-EGLR.202-03.png",
      "K-EGLR.202-04.png",
      "K-EGLR.202-05.png",
      "K-EGLR.202-06.png",
      "K-GELC.307-01.png"
    ],
    "web_es": "",
    "web_en": ""
  },
  {
    "id": "p1781037475837",
    "codigo": "K-GELC.307",
    "nombre": "Casa GLENDA & ELADIO",
    "tipologia": "Residential",
    "estado": "Construido",
    "anio_inicio": "2021",
    "anio_fin": "2022",
    "superficie": "392",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 21 40",
    "lat_hem": "S",
    "lon": "064 19 34",
    "lon_hem": "W",
    "altitud": "562",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-GELC.307-01.png",
      "K-GELC.307-02.png"
    ]
  },
  {
    "id": "p1781039870192",
    "codigo": "M-JQEP",
    "nombre": "JAQUE PRODUCTORA",
    "tipologia": "Otros",
    "estado": "Construido",
    "anio_inicio": "2008",
    "anio_fin": "2021",
    "superficie": "393",
    "ciudad": "Córdoba",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 59",
    "lat_hem": "S",
    "lon": "064 14 27",
    "lon_hem": "W",
    "altitud": "449",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "M-JQEP-01.png",
      "M-JQEP-02.png",
      "M-JQEP-03.png"
    ]
  },
  {
    "id": "p1782012017621",
    "codigo": "H-EF.CP",
    "nombre": "SPA HOTEL EL FARO",
    "tipologia": "H",
    "estado": "Activo",
    "anio_inicio": "2026",
    "anio_fin": "2026",
    "superficie": "365",
    "ciudad": "Villa Carlos Paz",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 24 15",
    "lat_hem": "S",
    "lon": "064 29 59",
    "lon_hem": "W",
    "altitud": "690",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "",
    "web_en": "",
    "imagenes": [
      "P-08-03 - H-JMCP-SPA-005-Escena 18_1.png",
      "P-08-04 - H-JMCP-SPA-005-Escena 26_1.png",
      "P-08-05 - H-JMCP-SPA-005-Escena 20_1.png",
      "P-08-06 - H-JMCP-SPA-005-Escena 22_1.png",
      "P-08-07 - H-JMCP-SPA-005-Escena 2_2.png",
      "P-08-08 - H-JMCP-SPA-005-Escena 19_1.png",
      "P-08-09 - H-JMCP-SPA-005-Escena 002-29_1.png",
      "P-08-10 - H-JMCP-SPA-005-Escena 10_2.png"
    ]
  }
];
