// Generado por CMOF Admin — 20/7/2026, 06:15:14
var proyectosData = [
  {
    "id": "p1780987587201",
    "codigo": "H-BÖDN",
    "nombre": "BÖDEN HOTEL & SPA",
    "tipologia": "H",
    "estado": "Construido",
    "anio_inicio": "2017",
    "anio_fin": "2021",
    "superficie": "5579",
    "ciudad": "Villa General Belgrano",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 57 32",
    "lat_hem": "S",
    "lon": "064 33 12",
    "lon_hem": "W",
    "altitud": "787",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "P-01-01 - BODEN HOTEL Y SPA-01.jpg",
      "P-01-02 - BODEN HOTEL Y SPA-02.jpg",
      "P-01-03 - BODEN HOTEL Y SPA-02.jpg",
      "P-01-03 - BODEN HOTEL Y SPA-03.jpg",
      "P-01-04 - BODEN HOTEL Y SPA-06.jpg",
      "P-01-04 - BODEN HOTEL Y SPA-07.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-12.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-14.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-15.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-16.jpg",
      "P-01-05 - BODEN HOTEL Y SPA-18.jpg",
      "P-01-06 - BODEN HOTEL Y SPA-11.jpg",
      "P-01-07 - BODEN HOTEL Y SPA-12.jpg"
    ],
    "web_es": "BÖDEN Hotel & Spa\nArquitectura hotelera boutique en Villa General Belgrano, Córdoba.\n\nBÖDEN Hotel & Spa nace de la búsqueda de una hospitalidad contemporánea profundamente vinculada con el paisaje serrano de Villa General Belgrano y con una idea de bienestar asociada a la calma, la naturaleza y el tiempo desacelerado. El proyecto propone una arquitectura moderna de materialidad cálida, concebida para integrarse con el entorno y potenciar sus cualidades como destino de turismo de montaña en Córdoba, Argentina.\n\nLa experiencia se estructura a partir de tres elementos esenciales —Tierra, Agua y Cielo—, que dan sentido a los espacios y al modo en que el huésped recorre y habita el conjunto. La luz natural, las visuales abiertas y las áreas destinadas al descanso forman parte de una misma narrativa arquitectónica, propia de un hotel boutique diseñado desde el lugar y no impuesto sobre él.\n\nDiseñado y dirigido por CMOF Architecture Office, el proyecto integra hospitalidad, spa y arquitectura residencial de montaña en un único activo hotelero, pensado desde su concepción como plataforma de valor: ubicación, tipología y escala fueron decisiones tomadas antes que el programa técnico, entendiendo que el lugar y la experiencia son los que sostienen la tarifa y la memoria de marca a largo plazo.\n\nMás que un edificio, BÖDEN busca construir una atmósfera. Una experiencia de lujo sereno, donde el diseño no persigue el exceso sino la autenticidad, y donde cada decisión espacial contribuye a generar bienestar, memoria y una conexión genuina con el lugar. El huésped no compra m², compra recuerdo , y sin ese activo memorable no hay plataforma que sostenga tarifa.",
    "web_en": "BÖDEN Hotel & Spa\nBoutique hospitality architecture in Villa General Belgrano, Córdoba.\n\nBÖDEN Hotel & Spa was born from the search for a contemporary hospitality deeply connected to the mountain landscape of Villa General Belgrano, and to an idea of wellbeing rooted in calm, nature, and slowed-down time. The project proposes a modern architecture of warm materiality, conceived to integrate with its surroundings and enhance its qualities as a mountain tourism destination in Córdoba, Argentina.\n\nThe experience is structured around three essential elements —Earth, Water and Sky— which give meaning to the spaces and to the way guests move through and inhabit the complex. Natural light, open views, and areas devoted to rest are all part of a single architectural narrative, true to a boutique hotel designed from the place itself, not imposed upon it.\n\nDesigned and directed by CMOF Architecture Office, the project integrates hospitality, spa, and mountain residential architecture into a single hotel asset, conceived from the outset as a value platform: location, typology, and scale were decisions made before the technical program, understanding that place and experience are what sustain rate and brand memory over time.\n\nMore than a building, BÖDEN seeks to build an atmosphere. A serene luxury experience, where design does not pursue excess but authenticity, and where every spatial decision contributes to wellbeing, memory, and a genuine connection to the place. The guest doesn't buy square meters, they buy a memory — and without that memorable asset, no platform can sustain rate."
  },
  {
    "id": "p1780987781964",
    "codigo": "K-EGSC",
    "nombre": "Casa ELENA & GUILLERMO",
    "tipologia": "K",
    "estado": "En obra",
    "anio_inicio": "2023",
    "anio_fin": "2026",
    "superficie": "430",
    "ciudad": "San Clemente",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 41 36",
    "lat_hem": "S",
    "lon": "064 38 21",
    "lon_hem": "W",
    "altitud": "996",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-EGSC-001.jpg",
      "K-EGSC-002.jpg",
      "K-EGSC-003.jpg",
      "K-EGSC-004.jpg",
      "K-EGSC-008.jpg",
      "K-EGSC-010.jpg",
      "K-EGSC-014.jpg",
      "K-EGSC-018.jpg",
      "K-EGSC-020.jpg",
      "K-EGSC-021.jpg",
      "K-EGSC-023.jpg",
      "K-EGSC-024.jpg",
      "K-EGSC-025.jpg",
      "K-EGSC-026.jpeg",
      "K-EGSC-033.jpeg",
      "K-EGSC-035.jpeg",
      "K-EGSC-036.jpeg"
    ],
    "web_es": "",
    "web_en": ""
  },
  {
    "id": "p1780988025043",
    "codigo": "K-GELC-307",
    "nombre": "Casa GLENDA & ELADIO - 307",
    "tipologia": "K",
    "estado": "Construido",
    "anio_inicio": "2022",
    "anio_fin": "2023",
    "superficie": "363",
    "ciudad": "La Cuesta - La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 21 40",
    "lat_hem": "S",
    "lon": "064 19 34",
    "lon_hem": "W",
    "altitud": "610",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-GELC.307-01.png",
      "K-GELC.307-02.png"
    ],
    "web_es": "",
    "web_en": ""
  },
  {
    "id": "p1780988370950",
    "codigo": "K-PMIY",
    "nombre": "Casa PABLO & RENATA",
    "tipologia": "K",
    "estado": "Construido",
    "anio_inicio": "2017",
    "anio_fin": "2019",
    "superficie": "316",
    "ciudad": "Inti Yaco - Calamuchita",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 56 50",
    "lat_hem": "S",
    "lon": "064 41 57",
    "lon_hem": "W",
    "altitud": "1129",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "imagenes": [
      "K-PMIY-01.png",
      "K-PMIY-02.png",
      "K-PMIY-03.png",
      "K-PMIY-04.png",
      "K-PMIY-05.png",
      "K-PMIY-06.png",
      "K-PMIY-07.png"
    ],
    "web_es": "",
    "web_en": ""
  },
  {
    "id": "p1782762743605",
    "codigo": "H-SEFCP",
    "nombre": "SPA HOTEL EL FARO",
    "tipologia": "H",
    "estado": "Proyecto",
    "anio_inicio": "2026",
    "anio_fin": "",
    "superficie": "525",
    "ciudad": "Villa Carlos Paz",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 24 16",
    "lat_hem": "S",
    "lon": "064 29 59",
    "lon_hem": "W",
    "altitud": "690",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "EL FARO Hotel – Spa & Wellness\n\nUn destino de bienestar diseñado para transformar la estadía en una experiencia memorable.\n\nEl Spa & Wellness del Hotel EL FARO fue concebido como la pieza central de la estrategia de remodelación y reposicionamiento del hotel, entendiendo a la arquitectura como una herramienta para generar valor a través de la experiencia. Más que un conjunto de instalaciones de bienestar, el proyecto propone un recorrido cuidadosamente diseñado que fortalece el vínculo emocional del huésped con el lugar, convirtiendo el relax y el bienestar en uno de los recuerdos más significativos de su estadía.\n\nLa secuencia espacial guía al usuario a través de un circuito integral de bienestar que combina experiencias de agua, calor y relajación. El recorrido incluye una piscina climatizada con jets de hidromasaje, burbujas y cascadas, complementada por sauna seco, sauna húmedo, ducha escocesa, ducha de sensaciones, salas de masajes individuales y para parejas, culminando en una sala de relax concebida como el cierre del recorrido y el momento de mayor contemplación.\n\nEn todo el proyecto, la arquitectura, la iluminación, la materialidad y la percepción sensorial trabajan de manera integrada para crear una atmósfera de calma, confort y desconexión. Cada espacio fue diseñado para acompañar una transición gradual desde el ritmo cotidiano hacia un estado de bienestar físico y mental, reforzando la identidad del hotel a través de una experiencia inmersiva y cuidadosamente planificada.\n\nComo parte de la remodelación integral y puesta en valor del emblemático Hotel EL FARO de Villa Carlos Paz, el spa aprovecha uno de los mayores atributos del edificio: sus excepcionales vistas panorámicas hacia las Sierras de Córdoba. La arquitectura enmarca el paisaje y convierte la cambiante luz natural —especialmente durante el atardecer— en un componente esencial de la experiencia, estableciendo un diálogo permanente entre bienestar, naturaleza y arquitectura.",
    "web_en": "",
    "imagenes": [
      "H-SEFCP-SPA-01.png",
      "H-SEFCP-SPA-02a.png",
      "H-SEFCP-SPA-02b.png",
      "H-SEFCP-SPA-03a.png",
      "H-SEFCP-SPA-03B.png",
      "H-SEFCP-SPA-04a.png",
      "H-SEFCP-SPA-04b-night.png",
      "H-SEFCP-SPA-06.png",
      "H-SEFCP-SPA-07.png",
      "H-SEFCP-SPA-08.png",
      "P-08-07-ALT-720.png",
      "P-08-08-ALT-720.png",
      "P-08-10-ALT-720.png"
    ]
  },
  {
    "id": "p1782789108878",
    "codigo": "K-EGLR-202",
    "nombre": "Casa ELENA & GUILLERMO - LR",
    "tipologia": "K",
    "estado": "Construido",
    "anio_inicio": "2012",
    "anio_fin": "2013",
    "superficie": "513",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 43",
    "lat_hem": "S",
    "lon": "064 18 54",
    "lon_hem": "W",
    "altitud": "506",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "",
    "web_en": "",
    "imagenes": [
      "K-EGLR.202-01.png",
      "K-EGLR.202-02.png",
      "K-EGLR.202-03.png",
      "K-EGLR.202-04.png",
      "K-EGLR.202-05.png",
      "K-EGLR.202-06.png"
    ]
  },
  {
    "id": "p1782789822024",
    "codigo": "M-JQEP",
    "nombre": "JAQUE CONTENT PRODUCTORA",
    "tipologia": "M",
    "estado": "Construido",
    "anio_inicio": "2008",
    "anio_fin": "2009",
    "superficie": "393",
    "ciudad": "Córdoba",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 59",
    "lat_hem": "S",
    "lon": "064 14 27",
    "lon_hem": "W",
    "altitud": "449",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "JAQUE Content – Estudio de Producción Audiovisual\n\nUn espacio creativo diseñado para la colaboración, la producción y la innovación.\n\nConcebido para JAQUE Content, este estudio de producción audiovisual integra en un único conjunto arquitectónico todas las etapas del proceso creativo: oficinas administrativas, laboratorios de producción y postproducción, estudios de grabación, camarines, vestuarios y áreas sociales. La propuesta busca combinar precisión técnica, flexibilidad funcional y una identidad arquitectónica contemporánea capaz de acompañar la dinámica de la industria audiovisual.\n\nLa nave de oficinas fue proyectada utilizando la técnica constructiva de **Rammed Earth** (tierra apisonada), con muros de 40 cm de espesor que aportan una fuerte identidad material y responden a criterios de sustentabilidad. La elevada inercia térmica de este sistema mejora el comportamiento energético del edificio, estabiliza las temperaturas interiores, reduce la demanda de climatización y proporciona un excelente aislamiento térmico y acústico, generando espacios de trabajo confortables durante todo el año.\n\nLos estudios de grabación fueron diseñados a partir de un análisis específico de la acústica, la geometría y la materialidad de sus envolventes, optimizando el control de reflexiones, la absorción sonora y el aislamiento entre ambientes. La incorporación de una parrilla técnica transitable en altura facilita el montaje y reconfiguración de iluminación, cámaras y equipamiento escénico, mientras que un sistema de tableros eléctricos independientes permite controlar con precisión la iluminación técnica y escenográfica requerida por cada producción.\n\nLa flexibilidad constituye una de las premisas centrales del proyecto. Las áreas de oficinas incorporan equipamiento móvil y una organización espacial adaptable que permite reconfigurar rápidamente los puestos de trabajo según el tamaño de los equipos y las necesidades de cada proyecto, favoreciendo entornos colaborativos capaces de evolucionar junto con los procesos creativos y productivos de la empresa.\n\nCreo que este texto posiciona mucho mejor el proyecto, porque no solo describe el programa, sino que explica **las decisiones de diseño** y el **valor arquitectónico** detrás de ellas. Es el tipo de narrativa que suele tener mejor recepción tanto en un portfolio profesional como en publicaciones internacionales.",
    "web_en": "",
    "imagenes": [
      "M-JQEP-01.png",
      "M-JQEP-02.png",
      "M-JQEP-03.png"
    ]
  },
  {
    "id": "p1782794442959",
    "codigo": "K-RDMO",
    "nombre": "Casa DONADIO MOLVENTO",
    "tipologia": "K",
    "estado": "En obra",
    "anio_inicio": "2024",
    "anio_fin": "2025",
    "superficie": "521",
    "ciudad": "Villa Ciudad Parque (MOLVENTO)",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 50 39",
    "lat_hem": "S",
    "lon": "064 31 34",
    "lon_hem": "W",
    "altitud": "788",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "",
    "web_en": "",
    "imagenes": [
      "K-RDMO-IMG-03-IA.png",
      "K-RDMO-IMG-02-IA.png",
      "K-RDMO-IMG-01-IA.png",
      "K-RDMO-PLN-00-PLANTA BAJA.png",
      "K-RDMO-PLN-01-FACHADA ESTE-1.png",
      "K-RDMO-PLN-02-VISTA SUR-1-1.png"
    ]
  },
  {
    "id": "p1782860430300",
    "codigo": "K-JPBLP",
    "nombre": "Casa BALDACINI - LA PANKANA",
    "tipologia": "K",
    "estado": "Proyecto",
    "anio_inicio": "2022",
    "anio_fin": "2022",
    "superficie": "335",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 22",
    "lat_hem": "S",
    "lon": "064 19 02",
    "lon_hem": "W",
    "altitud": "538",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "",
    "web_en": "",
    "imagenes": [
      "K-JPBP - IMG-IA-01.png",
      "K-JPBP - IMG-IA-02.png",
      "K-JPBP - IMG-IA-03.png",
      "K-JPBP - IMG-IA-04.png"
    ]
  },
  {
    "id": "p1782971910185",
    "codigo": "E-NAT-e1",
    "nombre": "EDIFICIO NATURE / e1",
    "tipologia": "K",
    "estado": "Proyecto",
    "anio_inicio": "2022",
    "anio_fin": "-",
    "superficie": "4700",
    "ciudad": "Asunción",
    "provincia": "DC",
    "pais": "Paraguay",
    "lat": "25 17 13",
    "lat_hem": "S",
    "lon": "57 35 44",
    "lon_hem": "W",
    "altitud": "96",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "EDIFICIO NATURE 2\n\nEdificio de uso mixto que combina Locales comerciales de doble altura en planta baja (2 unidades)  dos pisos de oficinas , diez niveles de departamentos de 1 y 2 dormitorios y un nivel de amenities y espacios comunes .\nSuperficiee:\nLocales: comerciales: 2 ud\nOficinas: (planta libre a subdividir)\nDptos 1 Dormitorio: 37 ud.\nDptos 2 Dormitorios: 19 ud\nCocheras: 19 ud",
    "web_en": "",
    "imagenes": [
      "E-NAT-E-IMG-IA-01.png",
      "E-NAT-E-IMG-IA-02.png",
      "E-NAT-E-IMG-IA-03.png",
      "E-NAT-E-IMG-IA-04.png",
      "E-NAT-E-IMG-IA-05.png"
    ]
  },
  {
    "id": "p1783004987164",
    "codigo": "K-PMLD",
    "nombre": "Casa MOTRICH - La Deseada",
    "tipologia": "K",
    "estado": "En obra",
    "anio_inicio": "2025",
    "anio_fin": "2026",
    "superficie": "353",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 20 36",
    "lat_hem": "S",
    "lon": "064 19 31",
    "lon_hem": "W",
    "altitud": "626",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "Casa MOTRICH\n\n(en Construcción)",
    "web_en": "",
    "imagenes": [
      "K-PMLD - IMG-IA-001.jpg",
      "K-PMLD - IMG-IA-002.png",
      "K-PMLD - IMG-IA-004.png"
    ]
  },
  {
    "id": "p1783264922446",
    "codigo": "E-NAT-E2",
    "nombre": "EDIFICIO NATURE / e2",
    "tipologia": "K",
    "estado": "Proyecto",
    "anio_inicio": "2022",
    "anio_fin": "-",
    "superficie": "4850",
    "ciudad": "Asunción",
    "provincia": "DC",
    "pais": "Paraguay",
    "lat": "25 17 13",
    "lat_hem": "S",
    "lon": "257 35 44",
    "lon_hem": "W",
    "altitud": "96",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "EDIFICIO NATURE 2\n\nEdificio de uso mixto que combina Locales comerciales de doble altura en planta baja (2 unidades)  dos pisos de oficinas , dos torres de  nueve y diez niveles de departamentos de 1 y 2 dormitorios y un nivel de amenities y espacios comunes con piscina en puente.\nSuperficie: 4850 m2\nLocales: comerciales: 2 ud\nOficinas: (planta libre a subdividir)\nDptos 1 Dormitorio: 39 ud.\nDptos 2 Dormitorios: 21 ud\nCocheras: 19 ud",
    "web_en": "",
    "imagenes": [
      "E-NAT-E2-IMG-IA-01.png",
      "E-NAT-E2-IMG-IA-06.png",
      "E-NAT-E2-IMG-IA-08.png",
      "E-NAT-E2-IMG-IA-07.png",
      "E-NAT-E2-IMG-IA-02.png",
      "E-NAT-E2-IMG-IA-03.png",
      "E-NAT-E2-IMG-IA-04.png",
      "E-NAT-E2-IMG-IA-05.png"
    ]
  },
  {
    "id": "p1783357336660",
    "codigo": "I-LAM-O",
    "nombre": "OFICINAS INDUSTRIA LAM SA",
    "tipologia": "O",
    "estado": "Proyecto",
    "anio_inicio": "2025",
    "anio_fin": "2026",
    "superficie": "516 m2",
    "ciudad": "Córdoba",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 24 12",
    "lat_hem": "S",
    "lon": "064 05 18",
    "lon_hem": "W",
    "altitud": "362",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "OFICINAS INDUSTRIA LAM SA\n\nNuevas oficinas administrativas de Instustria LAM SA.\nUbicadas en zona sur de la ciudad de Córdoba, desarrolladas en 2 plantas con una superficie total de 516 m2.\nRealizada con estructura de perfileria metálica de perfiles de alma llena y envolvente con sistema de paneles compuestos metalicos con aislante para muros y cubierta.",
    "web_en": "",
    "imagenes": [
      "I-LAM-O - 00.png",
      "I-LAM-O - 00-b.png",
      "I-LAM-O - 01.png",
      "I-LAM-O - 02.png",
      "I-LAM-O - 03.png",
      "I-LAM-O - 04.png"
    ]
  },
  {
    "id": "p1783693821021",
    "codigo": "K-JG-LC",
    "nombre": "Casa GHIONE - La Cuesta",
    "tipologia": "K",
    "estado": "Proyecto",
    "anio_inicio": "2021",
    "anio_fin": "2021",
    "superficie": "646 m2",
    "ciudad": "La Calera",
    "provincia": "Córdoba",
    "pais": "Argentina",
    "lat": "31 21 44",
    "lat_hem": "S",
    "lon": "064 19 38",
    "lon_hem": "W",
    "altitud": "614",
    "memoria_es": "",
    "memoria_en": "",
    "concepto_es": "",
    "concepto_en": "",
    "web_es": "Casa GHIONE",
    "web_en": "",
    "imagenes": [
      "K-JGLC-IMG-IA-01.png",
      "K-JGLC-IMG-IA-02.png",
      "K-JGLC-IMG-IA-03.png"
    ]
  }
];
